name: firstapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dio: ^5.0.0
  path_provider: ^2.0.13 # Use the latest version available
  flutter_secure_storage: ^8.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  file_picker: ^8.1.7
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.3
  flutter_pdfview: ^1.0.7

  supabase_flutter: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  